name: Renovate

on:
  schedule:
    - cron: "0 6-22/2 * * 1-5"
    - cron: "0 12-23/2 * * 0,6"
  push:
    branches:
      - 'main'
  issues:
    types:
      - edited
  workflow_call:
    inputs:
      runsOn:
        description: Define on which runner this workflow should run
        default: "ubuntu-latest"
        required: false
        type: string

concurrency:
  group: 'renovate'
  cancel-in-progress: true

jobs:
  renovate:
    name: Renovate
    runs-on: ${{ inputs.runsOn || 'ubuntu-latest' }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ secrets.RENOVATE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Renovate
        uses: WyriHaximus/github-action-renovatebot@09a77bf4996e884b5f1d6854638ca737289df3a1 # v0.15.0
        with:
          renovateAppToken: ${{ steps.app-token.outputs.token }}
